#!C:\Users\SyedaBushraFatima\Documents\AI in modern Software Development\Assignment 2 HuggingFace\C2D\c2d_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
